[template]
cargo_generate_version = "0.13.0"

[placeholders]
description = { type="string", prompt="A short description of the algorithm", default="" }
license = { type="string", prompt="Choose a license", default="" }
url = { type="string", prompt="Your project URL", default="" }
upstream_url = { type="string", prompt="Your project repository", default="" }

